# Your DataExtractor should follow the import convension
from dataextractors.Extractor import Extractor
from dataextractors.FossEventsExtractor import FossEventsExtractor
from dataextractors.FossForceExtractor import FossForceExtractor